image: java:latest

stages:
  - tex
  - assemble
  - build
  - javadoc
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

tex:
  image: tianon/latex
  stage: tex
  script:
    - cd doc
    - pdflatex doc/Architekturbeschreibung.tex
    - cd ..
  artifacts:
    paths:
      - doc/Architekturbeschreibung.pdf
      
assemble:
  stage: assemble
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
    
build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

javadoc:
  stage: javadoc
  script:
    - ./gradlew javadoc
  artifacts:
    paths:
      - build/doc/*


test:
  stage: test
  script:
    - ./gradlew check