image: java:latest

stages:
  - build
  - javadoc
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

javadoc:
  stage: javadoc
  script:
    - ./gradlew javadoc
  artifacts:
    paths:
      - build/doc/*
    expire_in: 1 week


test:
  stage: test
  script:
    - ./gradlew check